# File: .github/workflows/cron_job.yml

name: Cron Job

on:
  schedule:
    - cron: '0 */5 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate logs
        run: echo "This is a log message" >> logs.txt

      - name: Send email
        uses: dawidd6/action-send-mail@v2.2.0
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Logs for testvideoapp"
          body: "Attached are the logs for testvideoapp"
          to: "arslanmanzoor332@gmail.com"
          attachments: "logs.txt"
