# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - testvideoapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_DEV:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true

      - name: Build with dotnet
        run: dotnet build --configuration Release
        working-directory: "./testvideo"


      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp
        working-directory: "./testvideo"


      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy_DEV:
    runs-on: windows-latest
    needs: build_DEV
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'testvideoapp'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_0A51303B87C14E5F8918DB63F6EA391E }}
          package: .

      - task: PowerShell@2
         inputs:
        targetType: 'inline'
      script: |
        # Run your desired commands here
        $logs = Get-Content -Path 'path/to/your/logs.txt'
         Write-Host 'Logs:'
         Write-Host $logs

        # Send the output of the script via email
        Write-Host 'Sending email...'
        Send-MailMessage -To 'your-recipient-email-address@example.com' -From 'your-email-address@example.com' -Subject 'Cron job output' -Body "Hello, world!`n`n$logs" -SmtpServer 'smtp.office365.com' -UseSsl -Port 587 -Credential (Get-Credential)
  displayName: 'Run cron job'
    
    
    
env:
  TZ: 'UTC'
  schedule: '0 */10 * * *'
